worker_processes 10;
events {
    worker_connections 1024;
}
http {
    # HTTPS 代理
    server {
        listen 443 ssl;
        server_name api.openai.com;

        ssl_certificate     ../cert/api.openai.com.crt;
        ssl_certificate_key  ../cert/api.openai.com.key;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            proxy_pass https://integrate.api.nvidia.com;
            proxy_http_version 1.1;
            proxy_set_header Host $proxy_host;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Type $http_content_type;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
            proxy_buffering off;
            proxy_read_timeout 3600s;
        }

        location = /favicon.ico {
            return 204;
        }
    }
}